apiVersion: apps/v1
kind: Deployment
metadata:
  name: soon-app-deployment
  labels:
    app: soon-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: soon-app
  template:
    metadata:
      labels:
        app: soon-app
    spec:
      containers:
      - name: soon-app
        image: vishvaj1/soon-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: soon-app-service
spec:
  type: LoadBalancer
  selector:
    app: soon-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000